### ISSUE TITLE
[Bug] Unexpected Token 500 Error

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#3176]
**Description-**
Since the last release this 500 error code has appeared in our /app/api/logs/eAPD-API-error-0.log log twice. 
```
SyntaxError: Unexpected token a in JSON at position 205
    at JSON.parse (<anonymous>)
    at Object.write (/app/api/logger/winston.js:36:26)
    at Array.logRequest (/app/api/node_modules/morgan/index.js:130:14)
    at listener (/app/api/node_modules/on-finished/index.js:169:15)
    at onFinish (/app/api/node_modules/on-finished/index.js:100:5)
    at callback (/app/api/node_modules/ee-first/index.js:55:10)
    at ServerResponse.onevent (/app/api/node_modules/ee-first/index.js:93:5)
    at ServerResponse.emit (events.js:388:22)
    at ServerResponse.emit (domain.js:470:12)
    at onFinish (_http_outgoing.js:792:10)
```

This generates an AWS Alarm/Notification, but the site remains available, both front and back end.
**Type of Bug-**

- [ ] Accessibility
- [?] Functional
- [ ] Usability
- [?] API
- [ ] Regression

**Steps to reproduce-**

1. Log into AWS
2. Go to CloudWatch > Log Groups
3. Click on production/app/api/logs/eAPD-API-error-0.log
4. Find the InstanceID of the current Production instance (i-04eb0ee69c7de6ed5)
5. Gaze upon the juicy logs (may need to increase reporting window for appropriate juiciness(to be able to see the relevant error(s)))

**Role Affected-**

- [X] All
- [ ] Federal Admin
- [ ] State Admin
- [ ] State Staff
- [ ] State Contractor
- [ ] System Admin

**Environment-**

- [X] All
- [ ] PR #\_\_\_\_
- [ ] Staging
- [ ] Production

**Browser-**

- [ ] Firefox
- [X] Chrome
- [ ] IE

**Expected results-**
No unexpected tokens in a JSON at position 205

**Actual results-**
Unexpected token in a JSON at position 205

**Comment by cthulhuplus** [comment]
Same/similar errors reported on lines:
```
Unexpected token * ... at position 231
a at 196
a at 197
a at 205
. at 182
> at 213
> at 181
w at 194
```
![image.png](https://images.zenhubusercontent.com/5e9749aa5773ead7746338c1/9debe18d-ab62-43c1-b6db-6c516269f0c0)
