### ISSUE TITLE
[Bug] CloudWatch Errors

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#3283]
**Description-**
While in CloudWatch I discovered these two entries in the eAPD-API-error-0.log log. 

```
2021-07-15T09:17:15.013-04:00
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
```

```
2021-07-15T09:17:19.018-04:00
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:561:11)
    at ServerResponse.header (/app/api/node_modules/express/lib/response.js:771:10)
    at ServerResponse.json (/app/api/node_modules/express/lib/response.js:264:10)
    at ServerResponse.send (/app/api/node_modules/express/lib/response.js:158:21)
    at /app/api/routes/me/get.js:41:23
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Type of Bug-**

- [ ] Accessibility
- [ ] Functional
- [ ] Usability
- [ ] API
- [ ] Regression

**Steps to reproduce-**

1. Log into AWS CloudWatch
2. LogGroups > Prod > eAPD-API-error-0.log
3. Go to the time stamps

Don't know what triggered these unfortunately

**Role Affected-**

- [ ] All
- [ ] Federal Admin
- [ ] State Admin
- [ ] State Staff
- [ ] State Contractor
- [ ] System Admin

**Environment-**

- [ ] All
- [ ] PR #\_\_\_\_
- [ ] Staging
- [ ] Production

**Browser-**

- [ ] Firefox
- [ ] Chrome
- [ ] IE

**Expected results-**

**Actual results-**

**Related user story/bug-** (if applicable)

**Additional information-** (optional)

**Logs or error output/Screenshot/Video-** (at least 1 of these)

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by cthulhuplus** [comment]
This occurred again today:
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
```
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:561:11)
    at ServerResponse.header (/app/api/node_modules/express/lib/response.js:771:10)
    at ServerResponse.json (/app/api/node_modules/express/lib/response.js:264:10)
    at ServerResponse.send (/app/api/node_modules/express/lib/response.js:158:21)
    at /app/api/routes/me/get.js:41:23
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
